### ISSUE TITLE
Problem with manifest.json

### ISSUE THREAD

**Issue by mstr1** [JayeshLab/vue-crypto-dashboard#1]
Hi Jayesh,

You wrote a great application here! Really well done.
You might have realised already that there is a problem with your manifest.json file.
The paths in there are not resolving correctly and prevent the app from being installed as PWA on Android.

{
  "name": "vue-crypto-dashboard",
  "short_name": "vue-crypto-dashboard",
  "icons": [
    {
      "src": "/img/icons/android-chrome-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "/img/icons/android-chrome-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    }
  ],
  "start_url": "/index.html",
  "display": "standalone",
  "background_color": "#000000",
  "theme_color": "#4DBA87"
}

/index.html resolves here to https://jayeshlab.github.io/index.html
The same happens with the icon files.

Usually in Vue.js this could be solved by switching to ./index.html and the same for icons.

Again, thanks a lot for this great application.

**Comment by JayeshLab** [comment]
Thanks a lot for raising the issue, I have fixed the manifest.json
