### ISSUE TITLE
Error when unsubscribing from WS

### ISSUE THREAD

**Issue by bettimms** [JayeshLab/vue-crypto-dashboard#2]
When trying to unsubscribe from the websocket it's coming this error:

```js
WebSocket connection to 'wss://stream.binance.com:9443/ws/btcusdt@ticker' failed: Received a broken close frame containing a reserved status code.
```

Any idea why could this happen?

**Comment by JayeshLab** [comment]
Thanks for raising the issue. I have fixed it in api.js by passing CloseEvent status code with websocket close method `ws.close(1000, "");`

**Comment by bettimms** [comment]
Thanks. Solved the same day in the same way as well.
